### PR TITLE
Alternate approach to subset generation question

### PR DESCRIPTION
**Pull request by mihir2512**

### CODE REVIEW

**Comment by dhananjay8968** [comment]
you can watch Sanket Sir's Lecture sir discussed the same ques in class

**Comment by mihir2512** [comment]
> 
> @
> you can watch Sanket Sir's Lecture sir discussed the same ques in class

which date's lecture? what approach did sir teach?

**Review by ArV29 — COMMENTED** [review]
So, we would take a loop for 2^n iterations with iterator i,
Take the binary for each i,
And for that binary, print the indexes which are one,
right?

Seems like a great approach

**Comment by mihir2512** [comment]
> So, we would take a loop for 2^n iterations with iterator i,
> Take the binary for each i,
> And for that binary, print the indexes which are one,
> right?
> 
> Seems like a great approach

Yes, exactly

**Pull request merged**
